/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProcesoRouteImport } from './routes/proceso'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ValorSlugRouteImport } from './routes/valor.$slug'

const ProcesoRoute = ProcesoRouteImport.update({
  id: '/proceso',
  path: '/proceso',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ValorSlugRoute = ValorSlugRouteImport.update({
  id: '/valor/$slug',
  path: '/valor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/proceso': typeof ProcesoRoute
  '/valor/$slug': typeof ValorSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/proceso': typeof ProcesoRoute
  '/valor/$slug': typeof ValorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/proceso': typeof ProcesoRoute
  '/valor/$slug': typeof ValorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/proceso' | '/valor/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/proceso' | '/valor/$slug'
  id: '__root__' | '/' | '/proceso' | '/valor/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProcesoRoute: typeof ProcesoRoute
  ValorSlugRoute: typeof ValorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proceso': {
      id: '/proceso'
      path: '/proceso'
      fullPath: '/proceso'
      preLoaderRoute: typeof ProcesoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valor/$slug': {
      id: '/valor/$slug'
      path: '/valor/$slug'
      fullPath: '/valor/$slug'
      preLoaderRoute: typeof ValorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProcesoRoute: ProcesoRoute,
  ValorSlugRoute: ValorSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
